version: '3.9'
services:

  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - webnet

  db:
    image: postgres:15
    volumes:
      - ../data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=dbtenant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=protokong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - webnet

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - webnet
networks:
  webnet:




